### ISSUE TITLE
Status of ROS interface

### ISSUE THREAD

**Issue by ad-daniel** [opendr-eu/opendr#148]
List showing which tools currently provide a ROS interface.

**Perception:**

- [x] Face Detection
   - [x] RetinaFace
- [x] Face Recognition
   - [x] Face recognition https://github.com/tasostefas/opendr_internal/pull/147
- [x] Landmark based facial expression recognition
   - [x] Landmark based facial expression recognition
- [x] Human Pose Estimation
   - [x] Lightweight open pose
- [x] Video Activity Recognition https://github.com/tasostefas/opendr_internal/pull/156
   - [x] x3d
- [x] Online Video Activity Recognition
   - [x] cox3d
- [x] Skeleton based Action Recognition https://github.com/tasostefas/opendr_internal/pull/158
   - [x] spatio temporal GCN
- [x] Progressive Skeleton based Action Recognition https://github.com/tasostefas/opendr_internal/pull/158
   - [x] progressive spation temporal GCN
- [x] Speech recognition #175 
   - [x] quadraticselfonn
   - [x] matchboxnet
   - [x] edgesspeechnets
- [x] Heart Anomaly Detection https://github.com/tasostefas/opendr_internal/pull/155
   - [x] Neural bag-of-feature
   - [x] Gated Recurrent Unit
- [x] Semantic Scene segmentation https://github.com/tasostefas/opendr_internal/pull/152
   - [x] BiseNet
- [x] Object detection 2d
   - [x] Centernet
   - [x] SSD
   - [x] Yolov3
- [x] Efficient Panoptic Segmentation
   - [x] Panoptic segmentation
- [x] 3d Object Localization #179 
   - [x] Voxel object detection 3d
- [x] Object Tracking 2d/3d #179 and #163
   - [x] Deep sort
   - [x] Fair mot
   - [x] ab3dmot
- [x] Multimodal Human Centric Perception
  - [x] RGBD hand gesture https://github.com/tasostefas/opendr_internal/pull/153
- [x] Multimodal 2d object detection
  - [x] GEM
  - [x] Detr

**Control:**
- [x] Mobile manipulation
- [x] Single Demostration Grasping #172 

**Planning:**
- [x] End-to-End planner #82 

**Simulation:**
- [x] Human Model Generation

**Comment by passalis** [comment]
I updated the list with recent PRs adding more nodes. I checked the tasks for which there is an open PR, in order to keep track what is actually missing.

**Comment by passalis** [comment]
I see that we are no longer missing any ROS node. I am closing this issue for now.
